FROM ajcm/alpine-nginx:latest

WORKDIR '/app/html'

COPY ./template1/ ./template1/

## copy conf
COPY ./default.conf /etc/nginx/conf.d/default.conf

#COPY --from=builder /app/html /usr/share/nginx/html


EXPOSE 80
